### ISSUE TITLE
Unable to create an issue

### ISSUE THREAD

**Issue by Shawiizz** [hub4j/github-api#1018]
**Describe the bug**
I tried to create an issue in a repository but it's not working.

**To Reproduce**
1. Try to create an issue with the code

**Expected behavior**
It should create the issue

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 1.119

**Additional context**
My error : 
```
Exception in thread "main" org.kohsuke.github.GHFileNotFoundException: https://api.github.com/repos/MohistBOT/test/issues {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/issues#create-an-issue"}
	at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:492)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:420)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:363)
	at org.kohsuke.github.Requester.fetch(Requester.java:74)
	at org.kohsuke.github.GHIssueBuilder.create(GHIssueBuilder.java:99)
	at main.main(main.java:15)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/MohistBOT/test/issues
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.bodyStream(GitHubHttpUrlConnectionClient.java:197)
	at org.kohsuke.github.GitHubResponse$ResponseInfo.getBodyAsString(GitHubResponse.java:326)
	at org.kohsuke.github.GitHubResponse.parseBody(GitHubResponse.java:91)
	at org.kohsuke.github.Requester.lambda$fetch$1(Requester.java:74)
	at org.kohsuke.github.GitHubClient.createResponse(GitHubClient.java:461)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:412)
	... 4 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/MohistBOT/test/issues
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:69)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:400)
	... 4 more
```

My code :
```
GitHub github = new GitHubBuilder().withPassword("myusername", "mypassword").build();
github.getUser("MohistBOT").getRepository("test").createIssue("test").body("test").create();
```

**Comment by bitwiseman** [comment]
@Shawiizz  
Is it possible this is due to user name and password logins no longer supported on github.com: https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ ? 

Or are you using a token for your password?

**Comment by Shawiizz** [comment]
I'm using right username and password. But maybe with another auth alternative it will work ?

**Comment by Shawiizz** [comment]
Works fine with oauth token. Thanks !
