### ISSUE TITLE
Add sort to GHContentSearchBuilder

### ISSUE THREAD

**Issue by breandan** [hub4j/github-api#1088]
The GitHub search API has a [`sort` parameter](https://docs.github.com/en/rest/reference/search#search-code--parameters), which this API currently does not support. It would be nice to add it.

**Comment by bitwiseman** [comment]
Would look much like this: https://github.com/hub4j/github-api/blob/e5222398328111b6672e485578addfa4a226869d/src/main/java/org/kohsuke/github/GHIssueSearchBuilder.java#L83-L100

PRs welcome.

**Comment by breandan** [comment]
I'm having some trouble getting the tests to pass. When I run `mvn -D enable-ci clean install site`, I receive this error:

```
[ERROR] searchContent(org.kohsuke.github.GitHubTest)  Time elapsed: 0.083 s  <<< ERROR!
org.kohsuke.github.GHException: Failed to retrieve http://localhost:36511/search/code?sort=indexed&order=asc&q=addClass+in%3Afile+language%3Ajs+repo%3Ajquery%2Fjquery
        at org.kohsuke.github.GitHubPageIterator.fetch(GitHubPageIterator.java:155)
        at org.kohsuke.github.GitHubPageIterator.hasNext(GitHubPageIterator.java:91)
        at org.kohsuke.github.PagedSearchIterable$1.hasNext(PagedSearchIterable.java:86)
        at org.kohsuke.github.PagedIterator.fetch(PagedIterator.java:106)
        at org.kohsuke.github.PagedIterator.hasNext(PagedIterator.java:74)
        at org.kohsuke.github.PagedIterator.next(PagedIterator.java:82)
        at org.kohsuke.github.GitHubTest.searchContent(GitHubTest.java:106)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.kohsuke.github.junit.WireMockMultiServerRule$1.evaluate(WireMockMultiServerRule.java:69)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: org.kohsuke.github.GHFileNotFoundException: http://localhost:36511/search/code?sort=indexed&order=asc&q=addClass+in%3Afile+language%3Ajs+repo%3Ajquery%2Fjquery 
                                               Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
search_code                                                |
                                                           |
GET                                                        | GET
/search/code?q=addClass+in%3Afile+language%3Ajs+repo%3Ajq  | /search/code?sort=indexed&order=asc&q=addClass+in%3Afile+<<<<< URL does not match
uery%2Fjquery                                              | language%3Ajs+repo%3Ajquery%2Fjquery
                                                           |
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*;    | Accept: text/html, image/gif, image/jpeg, *; q=.2, */*;
q=.2                                                       | q=.2
                                                           |
                                                           |
-----------------------------------------------------------------------------------------------------------------------

        at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:482)
        at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:409)
        at org.kohsuke.github.GitHubPageIterator.fetch(GitHubPageIterator.java:144)
        ... 37 more
Caused by: java.io.FileNotFoundException: http://localhost:36511/search/code?sort=indexed&order=asc&q=addClass+in%3Afile+language%3Ajs+repo%3Ajquery%2Fjquery
        at java.base/jdk.internal.reflect.GeneratedConstructorAccessor92.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.bodyStream(GitHubHttpUrlConnectionClient.java:174)
        at org.kohsuke.github.GitHubResponse$ResponseInfo.getBodyAsString(GitHubResponse.java:314)
        at org.kohsuke.github.GitHubResponse.parseBody(GitHubResponse.java:92)
        at org.kohsuke.github.GitHubPageIterator.lambda$fetch$0(GitHubPageIterator.java:145)
        at org.kohsuke.github.GitHubClient.createResponse(GitHubClient.java:451)
        at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:401)
        ... 38 more
Caused by: java.io.FileNotFoundException: http://localhost:36511/search/code?sort=indexed&order=asc&q=addClass+in%3Afile+language%3Ajs+repo%3Ajquery%2Fjquery
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
        at org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:63)
        at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:389)
        ... 38 more
```

Do you have any suggestions?

**Comment by bitwiseman** [comment]
Create  a PR with your change.  
Your modifcation of the test is good but it changes the URL of the search, which results in Wiremock correctly saying it doesn't have stub responses that match the new URL.   You need to update test resource files to match the new URL.

**Comment by breandan** [comment]
Ah thanks, after updating the test resources the unit test is now passing as expected.
