### ISSUE TITLE
GHRelease.uploadAsset tries uploading to github.com for GHE repo

### ISSUE THREAD

**Issue by AdamBrousseau** [hub4j/github-api#1100]
**Describe the bug**
I have a groovy script that gets a repo, creates a release, and then uploads assets to the release. It works for github.com but when I try to point at a private GHE instance the upload falls back to github.com. The repo is found, the release is created, the uploadUrl returned [here](https://github.com/hub4j/github-api/blob/884248930e7c6c025693d4b453c06cd3e0a058be/src/main/java/org/kohsuke/github/GHRelease.java#L172) is `https://github.***.com/api/uploads/repos/***/***/releases/659238/assets{?name,label}` which looks correct, but when the upload is attempted [here](https://github.com/hub4j/github-api/blob/884248930e7c6c025693d4b453c06cd3e0a058be/src/main/java/org/kohsuke/github/GHRelease.java#L249) it fails.

```
Exception in thread "main" org.kohsuke.github.HttpException: {"message":"Bad credentials","request_id":"BD4F:30ED:54248:84035:6065E067","documentation_url":"https://docs.github.com/rest"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:703)
	at org.kohsuke.github.Requester._to(Requester.java:306)
	at org.kohsuke.github.Requester.to(Requester.java:247)
	at org.kohsuke.github.GHRelease.uploadAsset(GHRelease.java:144)
	at org.kohsuke.github.GHRelease.uploadAsset(GHRelease.java:131)
	at net.adoptopenjdk.release.UploadAdoptReleaseFiles$_uploadFiles_closure3.doCall(UploadFiles.groovy:100)
	at net.adoptopenjdk.release.UploadAdoptReleaseFiles$_uploadFiles_closure3.call(UploadFiles.groovy)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2296)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2281)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2322)
	at net.adoptopenjdk.release.UploadAdoptReleaseFiles.uploadFiles(UploadFiles.groovy:87)
	at net.adoptopenjdk.release.UploadAdoptReleaseFiles.access$0(UploadFiles.groovy)
	at net.adoptopenjdk.release.UploadAdoptReleaseFiles$_release_closure2.doCall(UploadFiles.groovy:43)
	at net.adoptopenjdk.release.UploadAdoptReleaseFiles$_release_closure2.call(UploadFiles.groovy)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:5929)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2373)
	at net.adoptopenjdk.release.UploadAdoptReleaseFiles.release(UploadFiles.groovy:36)
	at net.adoptopenjdk.release.UploadAdoptReleaseFiles$release.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
	at net.adoptopenjdk.release.UploadFiles.run(UploadFiles.groovy:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
	at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:423)
	at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
	at net.adoptopenjdk.release.UploadFiles.main(UploadFiles.groovy)
Caused by: org.kohsuke.github.HttpException: Server returned HTTP response code: 401, message: 'Unauthorized' for URL: https://uploads.github.com/repos/***/***/releases/659238/assets?name=***.tar.gz
```

**To Reproduce**
Using GitHub Enterprise Server 2.21.14

**Expected behavior**
Url should be the one returned by getUploadUrl

**Comment by AdamBrousseau** [comment]
Just realized that the original author is importing lib version 1.95 which has the upload url hardcoded
https://github.com/hub4j/github-api/blob/c1bab63ebdd9c93e49a5879331234de488e91590/src/main/java/org/kohsuke/github/GHRelease.java#L140

Sorry for the fluff.
