### ISSUE TITLE
Jenkins unable to resolve class org.kohsuke.github.GitHub.

### ISSUE THREAD

**Issue by orlandoacevedo-pge** [hub4j/github-api#1135]
**Describe the bug**
Jenkins fails to import org.kohsuke.github.GitHub class in Jenkins Job DSL.

**To Reproduce**
1. Using docker image: jenkins/jenkins:2.277.3-lts-alpine
2. Install Jenkins Plugin org.jenkins-ci.plugins:github-api:1.123
3. Using Jenkins Job DSL Playground
4. Run "import org.kohsuke.github.GitHub;"

**Expected behavior**
javaposse.jobdsl.dsl.DslException: startup failed:
script: 1: unable to resolve class org.kohsuke.github.GitHub
 @ line 1, column 1.
   import org.kohsuke.github.GitHub;
   ^

1 error

	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScriptEngine(AbstractDslScriptLoader.groovy:112)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader$_runScripts_closure1.doCall(AbstractDslScriptLoader.groovy:61)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts(AbstractDslScriptLoader.groovy:46)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader$runScripts$0.callCurrent(Unknown Source)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScript(AbstractDslScriptLoader.groovy:87)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader$runScript.call(Unknown Source)
	at com.sheehan.jobdsl.DslScriptExecutor.execute(DslScriptExecutor.groovy:27)
	at com.sheehan.jobdsl.ScriptExecutor$execute.call(Unknown Source)
	at Ratpack$_run_closure1$_closure3$_closure7$_closure8.doCall(Ratpack.groovy:32)
	at com.sun.proxy.$Proxy10.execute(Unknown Source)
	at ratpack.exec.internal.DefaultPromise$1.success(DefaultPromise.java:42)
	at ratpack.exec.Promise.lambda$null$9(Promise.java:304)
	at ratpack.exec.Downstream$1.success(Downstream.java:73)
	at ratpack.exec.Promise.lambda$null$9(Promise.java:304)
	at ratpack.exec.Downstream$1.success(Downstream.java:73)
	at ratpack.exec.internal.DefaultExecution$2.lambda$success$1(DefaultExecution.java:161)
	at ratpack.exec.internal.DefaultExecution$SingleEventExecStream.exec(DefaultExecution.java:419)
	at ratpack.exec.internal.DefaultExecution.exec(DefaultExecution.java:246)
	at ratpack.exec.internal.DefaultExecution.intercept(DefaultExecution.java:240)
	at ratpack.exec.internal.DefaultExecution.drain(DefaultExecution.java:220)
	at ratpack.exec.internal.DefaultExecution.access$100(DefaultExecution.java:45)
	at ratpack.exec.internal.DefaultExecution$SingleEventExecStream.resume(DefaultExecution.java:452)
	at ratpack.exec.internal.DefaultExecution$2.success(DefaultExecution.java:161)
	at ratpack.server.internal.RequestBody.complete(RequestBody.java:125)
	at ratpack.server.internal.RequestBody.add(RequestBody.java:76)
	at ratpack.server.internal.NettyHandlerAdapter.channelRead(NettyHandlerAdapter.java:84)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:155)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:155)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:155)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:155)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:950)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:818)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:338)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:254)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$0(DefaultExecController.java:113)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script: 1: unable to resolve class org.kohsuke.github.GitHub
 @ line 1, column 1.
   import org.kohsuke.github.GitHub;
   ^

1 error

	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.parseScript(AbstractDslScriptLoader.groovy:134)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScriptEngine(AbstractDslScriptLoader.groovy:101)
	... 49 more

**Desktop (please complete the following information):**
 - OS: kubectl version 
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T10:03:32Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
 - Browser safari 
 - Version 14.0.3 (15610.4.3.1.7, 15610)

**Additional context**
Jenkins DSL can import org.kohsuke.github.* but class object is still not found.

**Comment by orlandoacevedo-pge** [comment]
https://github.com/jenkinsci/job-dsl-plugin/blob/master/docs/Extending-the-DSL.md

Could the issue be that https://github.com/hub4j/github-api/blob/4261c42949915816a9f246eb14c3dfd21a637bc2/pom.xml needs a Job DSL extension point?

**Comment by orlandoacevedo-pge** [comment]
From reading the Jenkins Job DSL docs it looks like importing a package is not simple because of security restrictions.  I don't understand why the GitHub api package would not be a default package in the Job DSL?  But that is a question for the Job DSL Plugin dev team.  I will take this issue up with them.  Closing this ticket for now unless someone else would like to see the call available in the Job DSL plugin for Jenkins.

**Comment by orlandoacevedo-pge** [comment]
Closing issue.

Thanks
