### ISSUE TITLE
401 Bad credentials errors coming up since yesterday

### ISSUE THREAD

**Issue by AbdealiJK** [hub4j/github-api#1182]
**Describe the bug**
I have been using the ghprb plugins in our jenkins, and things have been working fine so far.
Since yesterday, I found that the once I create a PullRequest on github - the jenkins job was not starting.

On checking the logs, I am getting errors for the following URLs:
```
GitHub API request [anonymous]: GET https://api.github.com/users/AbdealiJK
GitHub API request [anonymous]: GET https://api.github.com/rate_limit
GitHub API request [anonymous]: GET https://api.github.com/repos/GITHUB_ORG/GITHUB_REPO/pulls/37/commits
GitHub API request [anonymous]: GET https://api.github.com/repos/GITHUB_ORG/GITHUB_REPO/pulls/37
```
The error is:
```
Caused: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/...
...
Caused: org.kohsuke.github.HttpException: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
```

Things I have checked:
 - Jenkins is receiving the webhooks correctly for ghprb, but when it is trying to process the pull request and create a job - it fails
 - The credentials configured in jenkins and github have not been changed
 - No Jenkins configs were changed for atleast the last week
 - After this issue arose - I've updated Jenkins and all plugins. Updating them did not fix the problem
 - When I login to the jenkins server and do `curl https://api.github.com/users/AbdealiJK` it works fine.

**Jenkins information (and git related plugins)**:
```
Jenkins 2.289.1
Git Parameter Plug-In (git-parameter): 0.9.13
Pipeline: GitHub (pipeline-github): 2.7
Git client plugin (git-client): 3.7.2
GitHub Pull Request Builder (ghprb): 1.42.2
GitHub Branch Source Plugin (github-branch-source): 2.11.1
Git plugin (git): 4.7.2
GitHub plugin (github): 1.33.1
Pipeline GitHub Notify Step Plugin (pipeline-githubnotify-step): 1.0.5
GIT server Plugin (git-server): 1.9
GitHub API Plugin (github-api): 1.123
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 91

Full log:
```
Jun 10, 2021 4:34:19 AM FINE org.jenkinsci.plugins.ghprb.GhprbTrigger$DescriptorImpl getRepoTriggers
Found project [JENKINS_PROJECT] for webhook repo [GITHUB_ORG/GITHUB_REPO]
Jun 10, 2021 4:34:19 AM INFO org.jenkinsci.plugins.ghprb.GhprbTrigger handlePR
Checking PR #37 for job JENKINS_PROJECT
Jun 10, 2021 4:34:19 AM FINE org.kohsuke.github.GitHubClient sendRequest
GitHub API request [anonymous]: GET https://api.github.com/users/AbdealiJK
Jun 10, 2021 4:34:19 AM FINE org.kohsuke.github.GitHubClient updateRateLimit
Rate limit now: GHRateLimit {core {remaining=45, limit=60, resetDate=Thu Jun 10 05:10:24 UTC 2021}, search {remaining=999999, limit=1000000, resetDate=Thu Jan 01 00:00:00 UTC 1970}, graphql {remaining=999999, limit=1000000, resetDate=Thu Jan 01 00:00:00 UTC 1970}, integrationManifest {remaining=999999, limit=1000000, resetDate=Thu Jan 01 00:00:00 UTC 1970}}
Jun 10, 2021 4:34:19 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbPullRequest getAuthorEmail
Unable to fetch author info for 37
Jun 10, 2021 4:34:19 AM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest 
Created Pull Request #37 on GITHUB_ORG/GITHUB_REPO by AbdealiJK () updated at: 6/9/21 1:17 PM SHA: 3b40c338bbd67f278f600ab6dce9d0dcf3b850fa
Jun 10, 2021 4:34:19 AM FINE org.kohsuke.github.GitHubClient sendRequest
GitHub API request [anonymous]: GET https://api.github.com/users/AbdealiJK
Jun 10, 2021 4:34:19 AM FINE org.kohsuke.github.GitHubClient updateRateLimit
Rate limit now: GHRateLimit {core {remaining=44, limit=60, resetDate=Thu Jun 10 05:10:24 UTC 2021}, search {remaining=999999, limit=1000000, resetDate=Thu Jan 01 00:00:00 UTC 1970}, graphql {remaining=999999, limit=1000000, resetDate=Thu Jan 01 00:00:00 UTC 1970}, integrationManifest {remaining=999999, limit=1000000, resetDate=Thu Jan 01 00:00:00 UTC 1970}}
Jun 10, 2021 4:34:19 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
Exception caught while updating the PR
java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/users/AbdealiJK
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:64)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:394)
Caused: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/users/AbdealiJK
	at sun.reflect.GeneratedConstructorAccessor90.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.bodyStream(GitHubHttpUrlConnectionClient.java:196)
	at org.kohsuke.github.GitHubResponse$ResponseInfo.getBodyAsString(GitHubResponse.java:314)
	at org.kohsuke.github.GitHubResponse.parseBody(GitHubResponse.java:121)
	at org.kohsuke.github.Requester.lambda$fetchInto$2(Requester.java:91)
	at org.kohsuke.github.GitHubClient.createResponse(GitHubClient.java:455)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:406)
Caused: org.kohsuke.github.HttpException: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
	at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:489)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:414)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:358)
	at org.kohsuke.github.Requester.fetchInto(Requester.java:91)
	at org.kohsuke.github.GHPerson.populate(GHPerson.java:56)
	at org.kohsuke.github.GHPerson.getName(GHPerson.java:208)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.updatePR(GhprbPullRequest.java:337)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:221)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.onPullRequestHook(GhprbRepository.java:398)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.handlePR(GhprbTrigger.java:747)
	at org.jenkinsci.plugins.ghprb.GhprbRootAction$2.run(GhprbRootAction.java:257)
```

**Comment by bitwiseman** [comment]
@AbdealiJK  
Did you change anything in your Jenkins config?  Or did this just start happening with no local changes.
