### ISSUE TITLE
use api to fetch issue list and get infinite loop

### ISSUE THREAD

**Issue by penkzhou** [hub4j/github-api#1344]
**Describe the bug**
searchIssues() api run with infinite loop

**To Reproduce**
run the code:

```
GitHub github = new GitHubBuilder()
                .withOAuthToken("YOUR_ACCESS_TOKEN")
                .build();
        List<GHIssue> issueResult = github.searchIssues().isOpen().sort(GHIssueSearchBuilder.Sort.CREATED).list().withPageSize(20).toList();
        for (GHIssue issue:issueResult) {
            System.out.println(issue.getTitle());
        }
```

**Expected behavior**
print 20 lines title.

**Real behavior**
the script is dead because of  infinite loop(and reach the github's api call limit:"You have exceeded a secondary rate limit. Please wait a few minutes before you try again.")

**Desktop (please complete the following information):**
 - OS:macOS 12.0.1

**Comment by bitwiseman** [comment]
@penkzhou 
We're going to need more details.
What does the output look like? Is there a stack trace?

What happens if you change the page size to 100?  
Also, the list of search results is probably very long.  If you `.toList()` on it, it is quite possible the output will be thousands of results.  "You have exceeded a secondary rate limit." is likely GitHub throttling you for API abuse.

**Comment by penkzhou** [comment]
Thank you for the in time response.
> What happens if you change the page size to 100?
yeah, when I change the page size to 100 the error occur less.  But it throw the error sometimes.

> What does the output look like? Is there a stack trace?

`
org.kohsuke.github.HttpException: {
  "documentation_url": "https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits",
  "message": "You have exceeded a secondary rate limit. Please wait a few minutes before you try again."
}


at org.kohsuke.github.GitHubConnectorResponseErrorHandler$1.onError(GitHubConnectorResponseErrorHandler.java:56)
	at org.kohsuke.github.GitHubClient.detectKnownErrors(GitHubClient.java:424)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:386)
	at org.kohsuke.github.GitHubPageIterator.fetch(GitHubPageIterator.java:142)
	at org.kohsuke.github.GitHubPageIterator.hasNext(GitHubPageIterator.java:89)
	at org.kohsuke.github.PagedSearchIterable$1.hasNext(PagedSearchIterable.java:86)
	at org.kohsuke.github.PagedIterator.fetch(PagedIterator.java:106)
	at org.kohsuke.github.PagedIterator.hasNext(PagedIterator.java:74)
	at org.kohsuke.github.PagedIterable.toArray(PagedIterable.java:81)
	at org.kohsuke.github.PagedIterable.toArray(PagedIterable.java:106)
	at org.kohsuke.github.PagedIterable.toList(PagedIterable.java:118)
	at data.IssuesRepositoryImpl$getIssues$1.invokeSuspend(IssuesRepository.kt:68)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at data.IssuesRepositoryImpl.getIssues(IssuesRepository.kt:65)
	at common.AppState$initData$1.invokeSuspend(AppState.kt:68)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

`

**Comment by penkzhou** [comment]
My intent is to fetch the issue list and make the pagination myself.

**Comment by bitwiseman** [comment]
I edited your comments to use [triple backticks](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) for multiline code.  

> My intent is to fetch the issue list and make the pagination myself.

What list of issues are you trying to get?  Using `searchIssues()` is very broad.  I suspect the length of that list is large which will result in problems.  

The page the error links too tells you that you're basically making too many requests, too quickly, to an endpoint that you shouldn't. 
https://docs.github.com/en/rest/overview/resources-in-the-rest-api#secondary-rate-limits

Making the pagination yourself means you're loading all the data then showing the user pages of it?  That is definitely an anti-pattern, not recommended.

**Comment by penkzhou** [comment]
thanks for your response. I'm making a desktop app using github api.the use scenario is when I click the issue tab,it just load the first page data of issue.

the result now is it fetch the first page data then continue fetch the second page automatically then third and so on.so i can't control the issue list call with page size api.
