### ISSUE TITLE
ghRepositoryStatistics.getCodeFrequency() always report a null pointer error

### ISSUE THREAD

**Issue by JasonWu0506** [hub4j/github-api#1545]
**Describe the bug**

**To Reproduce**

  GitHub github = new GitHubBuilder().withOAuthToken(strOAuthToken).build();
            ghRepository = github.getUser(strOrg).getRepository(strRepo);
           
           
            GHRepositoryStatistics ghRepositoryStatistics = ghRepository.getStatistics();
            List<GHRepositoryStatistics.CodeFrequency> codeFrequencies = ghRepositoryStatistics.getCodeFrequency();

Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.Arrays$ArrayList.<init>(Arrays.java:4137)
	at java.base/java.util.Arrays.asList(Arrays.java:4122)
	at org.kohsuke.github.GHRepositoryStatistics.getCodeFrequency(GHRepositoryStatistics.java:319)

 <dependency>
            <groupId> org.kohsuke </groupId>
            <artifactId> github-api </artifactId>
            <version>1.313 </version>
        </dependency>

**Expected behavior**

**Desktop (please complete the following information):**

**Additional context**

**Comment by bitwiseman** [comment]
Hm, we do test this code path: 
https://github.com/hub4j/github-api/blob/ee1f0685a8e9feb4bdd719470874efb86d9307e2/src/test/java/org/kohsuke/github/GHRepositoryStatisticsTest.java#L148

But it might not be with current data/behavior.  This line needs to be hardened to return `null` instead of throwing:
https://github.com/hub4j/github-api/blob/ee1f0685a8e9feb4bdd719470874efb86d9307e2/src/main/java/org/kohsuke/github/GHRepositoryStatistics.java#L313
