### ISSUE TITLE
OkHttpGitHubConnector throws NoSuchMethodError

### ISSUE THREAD

**Issue by Janik7777** [hub4j/github-api#1570]
**Describe the bug**
As I updated my code to get rid of the deprecatd OkHttpConnector and to use the new OkHttpGitHubConnector, following error occured:
```java
Exception in thread "main" java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(byte[])'
	at org.kohsuke.github.extras.okhttp3.OkHttpGitHubConnector.send(OkHttpGitHubConnector.java:88)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:432)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:403)
	at org.kohsuke.github.Requester.fetch(Requester.java:85)
	at org.kohsuke.github.GHIssueBuilder.create(GHIssueBuilder.java:108)
        ...
```
I looked into it and found that the [RequestBody](https://square.github.io/okhttp/3.x/okhttp/okhttp3/RequestBody.html) object needs the `MediaType: contentType` argument, but OkHttpGitHubConnector tries to `body = RequestBody.create(IOUtils.toByteArray(request.body()));`.

**To Reproduce**
1. Create a Github instance using GitHubBuilder() and OkHttpGitHubConnector
2. Use github api to create an issue for your repository
--> Error should occur

**Comment by gsmet** [comment]
I got this error once and IIRC it's because you are using an older version of Okhttp.

**Comment by Janik7777** [comment]
> I got this error once and IIRC it's because you are using an older version of Okhttp.

Thank you for your fast answer. I'll try it

**Comment by Janik7777** [comment]
Did work for me with "com.squareup.okhttp3:okhttp:4.10.0"

**Comment by bitwiseman** [comment]
Thanks all for the fast answer to this issue.
