### ISSUE TITLE
Addition of listCodeownersErrors()

### ISSUE THREAD

**Issue by michael-s-grant** [hub4j/github-api#1597]
I would like to contribute a method offering access to the [GitHub API call](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-codeowners-errors) `/repos/{owner}/{repo}/codeowners/errors`.

**Comment by michael-s-grant** [comment]
The [test repository](https://github.com/hub4j-test-org/github-api) does not have a `.github/CODEOWNERS` file to test against.  For unit testing I could therefore either add one, or manually edit the Wiremock data.  What's your preference?

**Comment by bitwiseman** [comment]
Add the file, that seems fine.

**Comment by bitwiseman** [comment]
I've invited you to the `hub4j-test-org`.

**Comment by robinvandenbogaard** [comment]
@bitwiseman the PR https://github.com/hub4j/github-api/pull/1604 closed the PR https://github.com/hub4j/github-api/pull/1579 instead of issue https://github.com/hub4j/github-api/issues/1579 (same number).

The PR https://github.com/hub4j/github-api/pull/1579 addresses issue https://github.com/hub4j/github-api/issues/1549. Wich now has a automatically closed PR with good fix (opiniated).

Please close this issue as it it addressed by https://github.com/hub4j/github-api/pull/1604.
Please reopen PR https://github.com/hub4j/github-api/pull/1579 and address it when you see fit.

**Comment by michael-s-grant** [comment]
Sorry about the confusion between pull request and issue numbers; this seems to derive from the instructions when opening a pull request 'If this PR fixes one or more issues, include "Fixes #" lines for each issue."'  But "#<number>" causes GitHub to introduce a link to the appropriately-numbered pull request, not issue.  I suggest you modify the instructions for pull requests.

**Comment by michael-s-grant** [comment]
I don't quite understand how my pull request in `hub4-test-org/github-api` ended up being merged into `hub4/github-api` rather than the originating repository.  I'm happy to run with the result, but it does mean my test runs against a different repository to all the others.

Anyhow, I have now tested and implemented my change, and recorded a Wiremock snapshot of the data.  Now I just need permission to push to `hub4j/github-api` too and I will submit a pull request.

**Comment by bitwiseman** [comment]
I merged it by mistake. `hub4j-test-org/github-api` is a fork  of `hub4j/github-api`, so PRs for branches in that repo default to targeting `hub4j`. Sorry, my bad. I'll revert it. Do make your tests run against `hub4j-test-org`.  Because of your permissions in `hub4j-test-org`, you can push directly to `main` in that repo. No PR needed. 

You shouldn't need more permissions to submit a PR for your feature to `hub4j`.  Push your changes to your personal fork of `github-api` and do a PR from there.

**Comment by michael-s-grant** [comment]
Fair enough.  I'm not used to working with forks in this way.

**Comment by michael-s-grant** [comment]
I have created a pull request now.  Note that there seems to be a general problem in the tests (meaning I could replicate it with a test other than the one I created for my code, by temporarily deleting the Wiremock data), which seems to be the result of the JSON returned by fetching the repository being truncated, and hence not valid JSON.  This problem is intermittent, but occurs most of the time; since, however, it is out of the scope of this issue, I have not endeavoured to fix it.

Here is a stack trace, should you find it helpful:

> org.kohsuke.github.HttpException: Server returned HTTP response code: 200, message: 'null' for URL: http://localhost:57673/repos/hub4j-test-org/github-api
> 
> 	at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:612)
> 	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:450)
> 	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:403)
> 	at org.kohsuke.github.Requester.fetch(Requester.java:85)
> 	at org.kohsuke.github.GHRepository.read(GHRepository.java:145)
> 	at org.kohsuke.github.GHPerson.getRepository(GHPerson.java:156)
> 	at org.kohsuke.github.GHCodeownersErrorTest.getRepository(GHCodeownersErrorTest.java:47)
> 	at org.kohsuke.github.GHCodeownersErrorTest.testGetCodeownersErrors(GHCodeownersErrorTest.java:20)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
> 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
> 	at org.kohsuke.github.junit.WireMockMultiServerRule$1.evaluate(WireMockMultiServerRule.java:113)
> 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
> 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
> 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
> 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
> 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
> 	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
> 	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
> 	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
> Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input: was expecting closing quote for a string value
>  at [Source: (String)"{"id":206888201,"node_id":"MDEwOlJlcG9zaXRvcnkyMDY4ODgyMDE=","name":"github-api","full_name":"hub4j-test-org/github-api","private":false,"owner":{"login":"hub4j-test-org","id":7544739,"node_id":"MDEyOk9yZ2FuaXphdGlvbjc1NDQ3Mzk=","avatar_url":"https://avatars.githubusercontent.com/u/7544739?v=4","gravatar_id":"","url":"http://localhost:57673/users/hub4j-test-org","html_url":"https://github.com/hub4j-test-org","followers_url":"http://localhost:57673/users/hub4j-test-org/followers","following_url":"[truncated 7692 chars]; line: 1, column: 8193] (through reference chain: org.kohsuke.github.GHRepository["parent"])
> 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
> 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1826)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:394)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
> 	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
> 	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105)
> 	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1546)
> 	at org.kohsuke.github.GitHubResponse.parseBody(GitHubResponse.java:104)
> 	at org.kohsuke.github.Requester.lambda$fetch$1(Requester.java:85)
> 	at org.kohsuke.github.GitHubClient.createResponse(GitHubClient.java:549)
> 	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:436)
> 	... 34 more
> Caused by: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: was expecting closing quote for a string value
>  at [Source: (String)"{"id":206888201,"node_id":"MDEwOlJlcG9zaXRvcnkyMDY4ODgyMDE=","name":"github-api","full_name":"hub4j-test-org/github-api","private":false,"owner":{"login":"hub4j-test-org","id":7544739,"node_id":"MDEyOk9yZ2FuaXphdGlvbjc1NDQ3Mzk=","avatar_url":"https://avatars.githubusercontent.com/u/7544739?v=4","gravatar_id":"","url":"http://localhost:57673/users/hub4j-test-org","html_url":"https://github.com/hub4j-test-org","followers_url":"http://localhost:57673/users/hub4j-test-org/followers","following_url":"[truncated 7692 chars]; line: 1, column: 8193]
> 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:696)
> 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipString(ReaderBasedJsonParser.java:2266)
> 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:936)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:399)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
> 	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:392)
> 	... 42 more

**Comment by michael-s-grant** [comment]
Hello.  Without wanting to chivvy you, could I remind you that pull request #1610 has been awaiting your approval for the last two weeks, just in case it had slipped off your radar.
