### ISSUE TITLE
org.kohsuke.github.HttpException for getOrganization

### ISSUE THREAD

**Issue by bisegni** [hub4j/github-api#1963]
**Describe the bug**
I have a code that worked to get organization information using github application installed into this application. Not it s not working anymore getting the error below:
Caused by: org.kohsuke.github.HttpException: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest","status":"401"}
	at org.kohsuke.github.GitHubConnectorResponseErrorHandler$1.onError(GitHubConnectorResponseErrorHandler.java:83)
	at org.kohsuke.github.GitHubClient.detectKnownErrors(GitHubClient.java:504)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:464)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:427)
	at org.kohsuke.github.Requester.fetch(Requester.java:85)
	at org.kohsuke.github.GitHub.getOrganization(GitHub.java:640)
	
using github  app key, id and installation id i can authenticate and get app installation information but when i try to get the organization i got error, below the installation with the information loaded:
```
appInstallation = {GHAppInstallation@18308} "GHAppInstallation@eb1306c[accessTokenUrl=https://api.github.com/app/installations/55541328/access_tokens,appId=1014645,events=[],htmlUrl=https://github.com/organizations/ad-build-test/settings/installations/55541328,permissions={members=WRITE, contents=WRITE, metadata=READ, pull_requests=WRITE, repository_hooks=WRITE, team_discussions=WRITE, organization_plan=READ, organization_hooks=WRITE, organization_events=READ, organization_secrets=WRITE, organization_projects=ADMIN, organization_codespaces=WRITE, organization_custom_roles=WRITE, organization_user_blocking=WRITE, organization_administration=WRITE, organization_custom_org_roles=WRITE, organization_actions_variables=WRITE, organization_custom_properties=ADMIN, organization_codespaces_secrets=WRITE, organization_dependabot_secrets=WRITE, organization_codespaces_settings=WRITE, organization_self_hosted_runners=WRITE, organization_announcement_banners=WRITE, organization_personal_access_tokens=WRITE, organization_copilot_seat_managemen"
 account = {GHUser@18330} "GHUser@5ee60e32[suspendedAt=<null>,bio=<null>,blog=<null>,company=<null>,email=<null>,followers=0,following=0,hireable=false,location=<null>,login=ad-build-test,name=<null>,type=Organization,createdAt=<null>,id=168671263,nodeId=O_kgDOCg24Hw,updatedAt=<null>,url=https://api.github.com/users/ad-build-test]"
 accessTokenUrl = "https://api.github.com/app/installations/55541328/access_tokens"
 repositoriesUrl = "https://api.github.com/installation/repositories"
 appId = 1014645
 targetId = 168671263
 targetType = {GHTargetType@18333} "ORGANIZATION"
 permissions = {LinkedHashMap@18334}  size = 26
 events = {ArrayList@18335}  size = 0
 singleFileName = null
 repositorySelection = {GHRepositorySelection@18336} "ALL"
 htmlUrl = "https://github.com/organizations/ad-build-test/settings/installations/55541328"
 suspendedAt = null
 suspendedBy = null
 responseHeaderFields = {Collections$UnmodifiableMap@18338}  size = 19
 url = null
 id = 55541328
 nodeId = null
 createdAt = "2024-10-03T00:29:22.000Z"
 updatedAt = "2024-10-03T02:20:09.000Z"
 root = {GitHub@18341} 
```

i have gave all the authorization  to ad-build-test organization but i receive always the same error, to note that the same code worked month ago. Any sugestion?

**Comment by bisegni** [comment]
i found the error, it appears to be on my mistake. I was not using the token form installation
