### ISSUE TITLE
Got MissingMethodException exception when use getReleaseByTagName() and getRelease()

### ISSUE THREAD

**Issue by gbyukg** [hub4j/github-api#458]
I'm facing a very strange problem when I use `getReleaseByTagName` and `getRelease` function in **Jenkins pipeline**.

In my Pipeline: 

``` java
import org.kohsuke.github.GitHub

def github = GitHub.connectToEnterpriseWithOAuth(
    'xxx',
    null,
    'xxx'
)
def repo = github.getRepository('xxx')
println(repo.getBranch('master'))
```
This works fine, I can get branch information correctly.

But when I tried to get release information by using `repo.getReleaseByTagName("v1.0.0")` function, I got `groovy.lang.MissingMethodException` error:

Below is error message:

```
hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: org.kohsuke.github.GHRepository.getReleaseByTagName() is applicable for argument types: (java.lang.String) values: [v1.0.0]
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:153)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:159)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at WorkflowScript.run(WorkflowScript:13)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.GeneratedMethodAccessor115.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$101(SandboxContinuable.java:34)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.lambda$run0$0(SandboxContinuable.java:59)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:58)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:332)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:83)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:244)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:232)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

The same thing also happens when I try to use `getRelease(100)` function.

Thanks.

**Comment by bitwiseman** [comment]
@gbyukg  It is not clear to my why this would happen.  We have test for basically exactly what you describe:
https://github.com/github-api/github-api/blob/5b53fba020003a520abc26966ac934d75b46da48/src/test/java/org/kohsuke/github/GHRepositoryTest.java#L172

It is likely the issue is due to a limitation or requirement of Jenkins Pipeline. 

Oh, hm.  I see you have a `hudson.remoting.ProxyException`. Are you trying to run the script above on an agent?

**Comment by bitwiseman** [comment]
Closing due to lack of response.

**Comment by alfresanc** [comment]
For future bug hunters on this, check package version and be sure you're using a not so old one and compatible with your use case and tooling:

HERE: https://mvnrepository.com/artifact/org.kohsuke/github-api/

@GrabResolver(name="repo.jenkins-ci.org",root='http://repo.jenkins-ci.org/public/')
@Grapes([
    @Grab(group='org.kohsuke', module='github-api', version='1.95')
])
