### ISSUE TITLE
http_proxy config not working

### ISSUE THREAD

**Issue by vijay-sapient** [hub4j/github-api#588]
I have http_proxy set up on both container and on java opts. but when using github api plugin. i see plugin is not respecting http_proxy configuration. everything else is working except for url https://api.github.com/rate_limit and https://api.github.com/user

Below is the error:
```
2019-11-01 10:18:20.327+0000 [id=466]	INFO	org.kohsuke.github.Requester#parse: timed out accessing https://api.github.com/user; will try 1 more time(s)
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:120)
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:450)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:399)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:527)
	at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
	at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
	at org.kohsuke.github.Requester.parse(Requester.java:615)
	at org.kohsuke.github.Requester.parse(Requester.java:607)
	at org.kohsuke.github.Requester._to(Requester.java:285)
	at org.kohsuke.github.Requester.to(Requester.java:247)
	at org.kohsuke.github.GitHub.getMyself(GitHub.java:384)
	at org.jenkinsci.plugins.github_branch_source.Connector.isCredentialValid(Connector.java:523)
	at org.jenkinsci.plugins.github_branch_source.Connector.checkConnectionValidity(Connector.java:550)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator.visitSources(GitHubSCMNavigator.java:922)
	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:488)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:277)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:164)
	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:969)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

it related to https://issues.jenkins-ci.org/browse/JENKINS-42089, Could anyone help on how this was resolved?

**Comment by bitwiseman** [comment]
This library isn't doing anything interesting with HTTP.  It is likely that this is a limitation in OkHttp 2.x or in Jenkins. There is a JIRA for switching `github_branch_source` to use OkHttp3, but it has not made progress recently - https://issues.jenkins-ci.org/browse/JENKINS-57411.  You can try the incremental build in that ticket to see if it helps.
