### ISSUE TITLE
Scan repositories fail

### ISSUE THREAD

**Issue by sandjaie** [hub4j/github-api#739]
**Describe the bug**
Plugin Version : 1.106

It is observed that the scan repository option is failing with the below error
```
ERROR: [Fri Mar 13 14:34:25 GMT 2020] Could not fetch branches from source 
java.lang.IllegalArgumentException: byteString == null
	at okio.Buffer.write(Buffer.java:787)
	at com.squareup.okhttp.Cache$Entry.readCertificateList(Cache.java:628)
	at com.squareup.okhttp.Cache$Entry.<init>(Cache.java:555)
	at com.squareup.okhttp.Cache.get(Cache.java:194)
	at com.squareup.okhttp.Cache$1.get(Cache.java:139)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:207)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:450)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:399)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:155)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:199)
	at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getHeaderField(DelegatingHttpsURLConnection.java:190)
	at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:25)
	at org.kohsuke.github.Requester.noteRateLimit(Requester.java:639)
	at org.kohsuke.github.Requester._fetch(Requester.java:508)
	at org.kohsuke.github.Requester._fetch(Requester.java:496)
	at org.kohsuke.github.Requester.fetch(Requester.java:412)
	at org.kohsuke.github.GitHub.getRateLimit(GitHub.java:441)
	at org.jenkinsci.plugins.github_branch_source.ApiRateLimitChecker$1.checkApiRateLimit(ApiRateLimitChecker.java:24)
	at org.jenkinsci.plugins.github_branch_source.Connector.checkApiRateLimit(Connector.java:566)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.retrieve(GitHubSCMSource.java:941)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:373)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:283)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:641)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:277)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:164)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1032)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
```

**To Reproduce**
1. Click on 'Scan Repository Now'
2. Go to 'Scan Repository Log'
3. See error

**Expected behavior**
To scan the repository.

**Possibly related to**
https://github.com/github-api/github-api/issues/265

**Comment by sandjaie** [comment]
This is fixed by deleting the cache `rm -rf /var/jenkins_home/org.jenkinsci.plugins.github_branch_source.GitHubSCMProbe.cache/*`

**Comment by bitwiseman** [comment]
I think it still might belong here.  We do caching at this level.

**Comment by bitwiseman** [comment]
@sandjaie 
This might be some kind of bug in OkHttp 2.x since that is what Jenkins is using.  
How often do you see this problem?

**Comment by bitwiseman** [comment]
Github-branch-sourcre has moved to okhttp3.  Please comment if you see this again.
