### ISSUE TITLE
Add support for Github Discussions API

### ISSUE THREAD

**Issue by cmoulliard** [hub4j/github-api#828]
## Feature request

Is it planned to support the Discussions API - https://developer.github.com/v3/teams/discussions/ ?

**Comment by bitwiseman** [comment]
We'd welcome PRs. 

Take a look at the [CONTRIBUTING.md](https://github.com/hub4j/github-api/blob/master/CONTRIBUTING.md).  

It should be pretty easy.  Looks like there are only a few endpoints.

**Comment by cmoulliard** [comment]
Questions @bitwiseman :

- Should we extend the `GHTeam` and/or `GHTeamBuilder` classes to support to perform CRUD operations on the `discussions` as they belong to a team - https://developer.github.com/v3/teams/discussions/#create-a-discussion or to have new classes `GHDiscussion` and `GHDiscussionBuilder` ?
- Should we add the CRUD operations to handle the discussions under the class - `GHOrganization` ?

**Comment by cmoulliard** [comment]
Why do I get this error when I execute the following request ?

Error
```
org.kohsuke.github.GHFileNotFoundException: https://api.github.com/orgs/snowdrop/teams/team-snowdrop/discussions {"message":"Not Found","documentation_url":"https://developer.github.com/v3/teams/discussions/#create-a-discussion"}

	at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:451)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:382)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:326)
	at org.kohsuke.github.Requester.fetch(Requester.java:71)
	at org.kohsuke.github.GHTeam.createDiscussion(GHTeam.java:330)
	at dev.snowdrop.github.GitHubDiscussionTest.testGitHubDiscussion(GitHubDiscussionTest.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.io.FileNotFoundException: https://api.github.com/orgs/snowdrop/teams/team-snowdrop/discussions
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1964)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1963)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1531)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.bodyStream(GitHubHttpUrlConnectionClient.java:197)
	at org.kohsuke.github.GitHubResponse$ResponseInfo.getBodyAsString(GitHubResponse.java:321)
	at org.kohsuke.github.GitHubResponse.parseBody(GitHubResponse.java:85)
	at org.kohsuke.github.Requester.lambda$fetch$1(Requester.java:71)
	at org.kohsuke.github.GitHubClient.createResponse(GitHubClient.java:420)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:374)
	... 27 more
Caused by: java.io.FileNotFoundException: https://api.github.com/orgs/snowdrop/teams/team-snowdrop/discussions
```

Code
```
    public void createDiscussion(String orgName, String teamName, String name) throws IOException {
        root.createRequest()
                .method("POST")
                .withUrlPath("/orgs/" + orgName + "/teams/" + teamName + "/discussions")
                .with("title", name)
                .with("body", "this is a dummy test")
                .fetch(GHDiscussion.class)
                .wrapUp(root);
    }
```

**Comment by bitwiseman** [comment]
@cmoulliard 

Look at `GHLabel` and the PR #724 for the best example I have my current design intent.  It is a little muddled because I updated an existing class.  The CRUD operations are encapsulated in the class, with `create()` and `read()` being `static` members.  The `set()/update()` and `delete()` are instance members.

**Comment by cmoulliard** [comment]
> The CRUD operations are encapsulated in the class, with `create()` and `read()` being `static` members. The `set()/update()` and `delete()` are instance members.

Is GHLAbel the best example as I see many fields methods deprecated - https://github.com/hub4j/github-api/blob/master/src/main/java/org/kohsuke/github/GHLabel.java#L136 ? @bitwiseman

**Comment by bitwiseman** [comment]
`@Preview @Deprecated` means they are new and subject to possible change. 
https://github.com/hub4j/github-
api/blob/master/src/main/java/org/kohsuke/github/GHLabel.java#L135-L136

These methods can and should be used but breaking changes may be made to them.

**Comment by cmoulliard** [comment]
Many thanks @bitwiseman. Did you see my questions on gitter ?

**Comment by bitwiseman** [comment]
@cmoulliard 



> * Should we extend the `GHTeam` and/or `GHTeamBuilder` classes to support to perform CRUD operations on the `discussions` as they belong to a team - https://developer.github.com/v3/teams/discussions/#create-a-discussion or to have new classes `GHDiscussion` and `GHDiscussionBuilder` ?

It looks like like you when with `GHDiscussion` and `GHDiscussionBuilder`.  That is what I would have suggested.  You should add  `createDiscussion()` and `getDiscussion()` methods to `GHTeam`, however they should be wrappers around methods on `GHDiscussion` and `GHDiscussionBuilder` - we want the knowledge of Discussions be encapsulated in discussions.  The is the most important part of the `GHLabel change.  Rather than have `GHRepository` have label queries in it, `GHRepository` should call `GHLabel` to do the work.  

https://github.com/hub4j/github-api/blob/7a650132c52d40c50173268b3cee368c009b7637/src/main/java/org/kohsuke/github/GHRepository.java#L1891-L1904

https://github.com/bitwiseman/github-api/blob/772272ff36f48424c99115970b481a33f5c49ae0/src/main/java/org/kohsuke/github/GHLabel.java#L124-L139

You do not have to use the `AbstractBuilder`, but we want the logic for a class mostly held in that class.  

> * Should we add the CRUD operations to handle the discussions under the class - `GHOrganization` ?

You could add helper methods to `GHOrganization` that take a `team_slug` and so on. It is up to you. More surface area needing tests.

**Comment by cmoulliard** [comment]
> You do not have to use the `AbstractBuilder`, but we want the logic for a class mostly held in that class.

ok but then what is the purpose of the `GHLabelBuilder` which extends `AbstractBuilder<GHLabel, S>` ? @bitwiseman

**Comment by cmoulliard** [comment]
The PR #834 includes the following CRUD operations:

- `createDiscussion(String name)`
- `getDiscussion(String discussionId)` 
- `deleteDiscussion(String number)`
- `updateDiscussion()`
- `listDiscussions()`

**Comment by cmoulliard** [comment]
> Okay, so the logic is in two files

Many thanks for the response :-)
