### ISSUE TITLE
GHPullRequest.getLabels fails for parsed events

### ISSUE THREAD

**Issue by seregamorph** [hub4j/github-api#943]
**Describe the bug**
Consider a payload for `X-GitHub-Event: pull_request` webhook (exact payload in first comment). It has path `/pull_request/labels`:
```json
...
    "labels": [
      {
        "id": 1545228115,
        "node_id": "MDU6TGFiZWwxNTQ1MjI4MTE1",
        "url": "https://api.github.com/repos/trilogy-group/devfactory-codeserver-framework/labels/rest%20api",
        "name": "rest api",
        "color": "0f288c",
        "default": false,
        "description": ""
      }
    ],
...
```
To parse this object I call:
```
GHEventPayload.PullRequest pullRequest = GitHub.offline()
                .parseEventPayload(payloadReader, GHEventPayload.PullRequest.class);
```
Then if I call `pullRequest.getPullRequest().getLabels()` it fails:
```
org.kohsuke.github.GHIOException: Offline
	at org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:64)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:400)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:363)
	at org.kohsuke.github.Requester.fetchInto(Requester.java:89)
	at org.kohsuke.github.GHPullRequest.fetchIssue(GHPullRequest.java:631)
	at org.kohsuke.github.GHPullRequest.getLabels(GHPullRequest.java:182)
	at com.trilogy.restapilistener.controllers.GitHubHookControllerKt.hasRestApiLabel(GitHubHookController.kt:437)
	...
Caused by: java.io.IOException: Offline
	at org.kohsuke.github.HttpConnector.lambda$static$1(HttpConnector.java:39)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.setupConnection(GitHubHttpUrlConnectionClient.java:113)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:61)
	... 66 common frames omitted
```
But the data is correct before the call. Enforced `GHPullRequest.fetchIssue()` breaks things.

**To Reproduce**
1. Set up webhook on gitHub repository with type pull request
![Screen Shot 2020-09-24 at 21 27 19](https://user-images.githubusercontent.com/2844909/94184558-c4ee4100-feac-11ea-9274-82ef89f2de31.png)
2. Fire pull request event, e.g. open a pull request with non-empty labels, or edit existing PR
3. handle the payload via `GitHub.offline().parseEventPayload` and try to get labels

**Expected behavior**
`pullRequest.getPullRequest().getLabels()` call gives a list of parsed labels (name)

**Desktop (please complete the following information):**

**Additional context**

**Comment by seregamorph** [comment]
Header: `X-GitHub-Event: pull_request`
with payload
```
{
  "action": "opened",
  "number": 1832,
  "pull_request": {
    "url": "https://api.github.com/repos/company-group/project-project-project/pulls/1832",
    "id": 482513034,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NDgyNTEzMDM0",
    "html_url": "https://github.com/company-group/project-project-project/pull/1832",
    "diff_url": "https://github.com/company-group/project-project-project/pull/1832.diff",
    "patch_url": "https://github.com/company-group/project-project-project/pull/1832.patch",
    "issue_url": "https://api.github.com/repos/company-group/project-project-project/issues/1832",
    "number": 1832,
    "state": "open",
    "locked": false,
    "title": "CSRV-20350 : ChangeEntry api - summary",
    "user": {
      "login": "seregamorph",
      "id": 2844909,
      "node_id": "MDQ6VXNlcjM3MzE3OTIw",
      "avatar_url": "https://avatars0.githubusercontent.com/u/2844909?s=88&v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/seregamorph",
      "html_url": "https://github.com/seregamorph",
      "followers_url": "https://api.github.com/users/seregamorph/followers",
      "following_url": "https://api.github.com/users/seregamorph/following{/other_user}",
      "gists_url": "https://api.github.com/users/seregamorph/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/seregamorph/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/seregamorph/subscriptions",
      "organizations_url": "https://api.github.com/users/seregamorph/orgs",
      "repos_url": "https://api.github.com/users/seregamorph/repos",
      "events_url": "https://api.github.com/users/seregamorph/events{/privacy}",
      "received_events_url": "https://api.github.com/users/seregamorph/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "https://jira.devfactory.com/browse/CSRV-20350",
    "created_at": "2020-09-09T05:17:34Z",
    "updated_at": "2020-09-09T05:17:34Z",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": null,
    "assignee": {
      "login": "seregamorph",
      "id": 2844909,
      "node_id": "MDQ6VXNlcjM3MzE3OTIw",
      "avatar_url": "https://avatars0.githubusercontent.com/u/2844909?s=88&v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/seregamorph",
      "html_url": "https://github.com/seregamorph",
      "followers_url": "https://api.github.com/users/seregamorph/followers",
      "following_url": "https://api.github.com/users/seregamorph/following{/other_user}",
      "gists_url": "https://api.github.com/users/seregamorph/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/seregamorph/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/seregamorph/subscriptions",
      "organizations_url": "https://api.github.com/users/seregamorph/orgs",
      "repos_url": "https://api.github.com/users/seregamorph/repos",
      "events_url": "https://api.github.com/users/seregamorph/events{/privacy}",
      "received_events_url": "https://api.github.com/users/seregamorph/received_events",
      "type": "User",
      "site_admin": false
    },
    "assignees": [
      {
        "login": "seregamorph",
        "id": 2844909,
        "node_id": "MDQ6VXNlcjM3MzE3OTIw",
        "avatar_url": "https://avatars0.githubusercontent.com/u/2844909?s=88&v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/seregamorph",
        "html_url": "https://github.com/seregamorph",
        "followers_url": "https://api.github.com/users/seregamorph/followers",
        "following_url": "https://api.github.com/users/seregamorph/following{/other_user}",
        "gists_url": "https://api.github.com/users/seregamorph/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/seregamorph/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seregamorph/subscriptions",
        "organizations_url": "https://api.github.com/users/seregamorph/orgs",
        "repos_url": "https://api.github.com/users/seregamorph/repos",
        "events_url": "https://api.github.com/users/seregamorph/events{/privacy}",
        "received_events_url": "https://api.github.com/users/seregamorph/received_events",
        "type": "User",
        "site_admin": false
      }
    ],
    "requested_reviewers": [
      {
        "login": "schernov-xo",
        "id": 41187778,
        "node_id": "MDQ6VXNlcjQxMTg3Nzc4",
        "avatar_url": "https://avatars3.githubusercontent.com/u/41187778?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/schernov-xo",
        "html_url": "https://github.com/schernov-xo",
        "followers_url": "https://api.github.com/users/schernov-xo/followers",
        "following_url": "https://api.github.com/users/schernov-xo/following{/other_user}",
        "gists_url": "https://api.github.com/users/schernov-xo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/schernov-xo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/schernov-xo/subscriptions",
        "organizations_url": "https://api.github.com/users/schernov-xo/orgs",
        "repos_url": "https://api.github.com/users/schernov-xo/repos",
        "events_url": "https://api.github.com/users/schernov-xo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/schernov-xo/received_events",
        "type": "User",
        "site_admin": false
      }
    ],
    "requested_teams": [],
    "labels": [
      {
        "id": 1545228115,
        "node_id": "MDU6TGFiZWwxNTQ1MjI4MTE1",
        "url": "https://api.github.com/repos/company-group/project-project-project/labels/rest%20api",
        "name": "rest api",
        "color": "0f288c",
        "default": false,
        "description": ""
      }
    ],
    "milestone": null,
    "draft": true,
    "commits_url": "https://api.github.com/repos/company-group/project-project-project/pulls/1832/commits",
    "review_comments_url": "https://api.github.com/repos/company-group/project-project-project/pulls/1832/comments",
    "review_comment_url": "https://api.github.com/repos/company-group/project-project-project/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/company-group/project-project-project/issues/1832/comments",
    "statuses_url": "https://api.github.com/repos/company-group/project-project-project/statuses/990cc7fbf549145e5264c1b9a31ff9dd6d8bfea4",
    "head": {
      "label": "company-group:feature/CSRV-20350-change-entries-summaries",
      "ref": "feature/CSRV-20350-change-entries-summaries",
      "sha": "990cc7fbf549145e5264c1b9a31ff9dd6d8bfea4",
      "user": {
        "login": "company-group",
        "id": 22237814,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjIyMjM3ODE0",
        "avatar_url": "https://avatars1.githubusercontent.com/u/22237814?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/company-group",
        "html_url": "https://github.com/company-group",
        "followers_url": "https://api.github.com/users/company-group/followers",
        "following_url": "https://api.github.com/users/company-group/following{/other_user}",
        "gists_url": "https://api.github.com/users/company-group/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/company-group/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/company-group/subscriptions",
        "organizations_url": "https://api.github.com/users/company-group/orgs",
        "repos_url": "https://api.github.com/users/company-group/repos",
        "events_url": "https://api.github.com/users/company-group/events{/privacy}",
        "received_events_url": "https://api.github.com/users/company-group/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 84682874,
        "node_id": "MDEwOlJlcG9zaXRvcnk4NDY4Mjg3NA==",
        "name": "project-project-project",
        "full_name": "company-group/project-project-project",
        "private": true,
        "owner": {
          "login": "company-group",
          "id": 22237814,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjIyMjM3ODE0",
          "avatar_url": "https://avatars1.githubusercontent.com/u/22237814?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/company-group",
          "html_url": "https://github.com/company-group",
          "followers_url": "https://api.github.com/users/company-group/followers",
          "following_url": "https://api.github.com/users/company-group/following{/other_user}",
          "gists_url": "https://api.github.com/users/company-group/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/company-group/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/company-group/subscriptions",
          "organizations_url": "https://api.github.com/users/company-group/orgs",
          "repos_url": "https://api.github.com/users/company-group/repos",
          "events_url": "https://api.github.com/users/company-group/events{/privacy}",
          "received_events_url": "https://api.github.com/users/company-group/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/company-group/project-project-project",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/company-group/project-project-project",
        "forks_url": "https://api.github.com/repos/company-group/project-project-project/forks",
        "keys_url": "https://api.github.com/repos/company-group/project-project-project/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/company-group/project-project-project/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/company-group/project-project-project/teams",
        "hooks_url": "https://api.github.com/repos/company-group/project-project-project/hooks",
        "issue_events_url": "https://api.github.com/repos/company-group/project-project-project/issues/events{/number}",
        "events_url": "https://api.github.com/repos/company-group/project-project-project/events",
        "assignees_url": "https://api.github.com/repos/company-group/project-project-project/assignees{/user}",
        "branches_url": "https://api.github.com/repos/company-group/project-project-project/branches{/branch}",
        "tags_url": "https://api.github.com/repos/company-group/project-project-project/tags",
        "blobs_url": "https://api.github.com/repos/company-group/project-project-project/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/company-group/project-project-project/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/company-group/project-project-project/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/company-group/project-project-project/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/company-group/project-project-project/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/company-group/project-project-project/languages",
        "stargazers_url": "https://api.github.com/repos/company-group/project-project-project/stargazers",
        "contributors_url": "https://api.github.com/repos/company-group/project-project-project/contributors",
        "subscribers_url": "https://api.github.com/repos/company-group/project-project-project/subscribers",
        "subscription_url": "https://api.github.com/repos/company-group/project-project-project/subscription",
        "commits_url": "https://api.github.com/repos/company-group/project-project-project/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/company-group/project-project-project/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/company-group/project-project-project/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/company-group/project-project-project/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/company-group/project-project-project/contents/{+path}",
        "compare_url": "https://api.github.com/repos/company-group/project-project-project/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/company-group/project-project-project/merges",
        "archive_url": "https://api.github.com/repos/company-group/project-project-project/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/company-group/project-project-project/downloads",
        "issues_url": "https://api.github.com/repos/company-group/project-project-project/issues{/number}",
        "pulls_url": "https://api.github.com/repos/company-group/project-project-project/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/company-group/project-project-project/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/company-group/project-project-project/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/company-group/project-project-project/labels{/name}",
        "releases_url": "https://api.github.com/repos/company-group/project-project-project/releases{/id}",
        "deployments_url": "https://api.github.com/repos/company-group/project-project-project/deployments",
        "created_at": "2017-03-11T22:06:17Z",
        "updated_at": "2020-09-07T17:43:40Z",
        "pushed_at": "2020-09-09T05:16:47Z",
        "git_url": "git://github.com/company-group/project-project-project.git",
        "ssh_url": "git@github.com:company-group/project-project-project.git",
        "clone_url": "https://github.com/company-group/project-project-project.git",
        "svn_url": "https://github.com/company-group/project-project-project",
        "homepage": "http://codeserver.devfactory.com",
        "size": 123370,
        "stargazers_count": 1,
        "watchers_count": 1,
        "language": "Java",
        "has_issues": false,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "forks_count": 3,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 3,
        "license": null,
        "forks": 3,
        "open_issues": 3,
        "watchers": 1,
        "default_branch": "master",
        "allow_squash_merge": true,
        "allow_merge_commit": false,
        "allow_rebase_merge": false,
        "delete_branch_on_merge": false
      }
    },
    "base": {
      "label": "company-group:master",
      "ref": "master",
      "sha": "cd338b6c0f84fbb9c945dbe92659a58e19ac45a1",
      "user": {
        "login": "company-group",
        "id": 22237814,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjIyMjM3ODE0",
        "avatar_url": "https://avatars1.githubusercontent.com/u/22237814?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/company-group",
        "html_url": "https://github.com/company-group",
        "followers_url": "https://api.github.com/users/company-group/followers",
        "following_url": "https://api.github.com/users/company-group/following{/other_user}",
        "gists_url": "https://api.github.com/users/company-group/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/company-group/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/company-group/subscriptions",
        "organizations_url": "https://api.github.com/users/company-group/orgs",
        "repos_url": "https://api.github.com/users/company-group/repos",
        "events_url": "https://api.github.com/users/company-group/events{/privacy}",
        "received_events_url": "https://api.github.com/users/company-group/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 84682874,
        "node_id": "MDEwOlJlcG9zaXRvcnk4NDY4Mjg3NA==",
        "name": "project-project-project",
        "full_name": "company-group/project-project-project",
        "private": true,
        "owner": {
          "login": "company-group",
          "id": 22237814,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjIyMjM3ODE0",
          "avatar_url": "https://avatars1.githubusercontent.com/u/22237814?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/company-group",
          "html_url": "https://github.com/company-group",
          "followers_url": "https://api.github.com/users/company-group/followers",
          "following_url": "https://api.github.com/users/company-group/following{/other_user}",
          "gists_url": "https://api.github.com/users/company-group/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/company-group/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/company-group/subscriptions",
          "organizations_url": "https://api.github.com/users/company-group/orgs",
          "repos_url": "https://api.github.com/users/company-group/repos",
          "events_url": "https://api.github.com/users/company-group/events{/privacy}",
          "received_events_url": "https://api.github.com/users/company-group/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/company-group/project-project-project",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/company-group/project-project-project",
        "forks_url": "https://api.github.com/repos/company-group/project-project-project/forks",
        "keys_url": "https://api.github.com/repos/company-group/project-project-project/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/company-group/project-project-project/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/company-group/project-project-project/teams",
        "hooks_url": "https://api.github.com/repos/company-group/project-project-project/hooks",
        "issue_events_url": "https://api.github.com/repos/company-group/project-project-project/issues/events{/number}",
        "events_url": "https://api.github.com/repos/company-group/project-project-project/events",
        "assignees_url": "https://api.github.com/repos/company-group/project-project-project/assignees{/user}",
        "branches_url": "https://api.github.com/repos/company-group/project-project-project/branches{/branch}",
        "tags_url": "https://api.github.com/repos/company-group/project-project-project/tags",
        "blobs_url": "https://api.github.com/repos/company-group/project-project-project/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/company-group/project-project-project/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/company-group/project-project-project/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/company-group/project-project-project/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/company-group/project-project-project/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/company-group/project-project-project/languages",
        "stargazers_url": "https://api.github.com/repos/company-group/project-project-project/stargazers",
        "contributors_url": "https://api.github.com/repos/company-group/project-project-project/contributors",
        "subscribers_url": "https://api.github.com/repos/company-group/project-project-project/subscribers",
        "subscription_url": "https://api.github.com/repos/company-group/project-project-project/subscription",
        "commits_url": "https://api.github.com/repos/company-group/project-project-project/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/company-group/project-project-project/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/company-group/project-project-project/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/company-group/project-project-project/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/company-group/project-project-project/contents/{+path}",
        "compare_url": "https://api.github.com/repos/company-group/project-project-project/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/company-group/project-project-project/merges",
        "archive_url": "https://api.github.com/repos/company-group/project-project-project/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/company-group/project-project-project/downloads",
        "issues_url": "https://api.github.com/repos/company-group/project-project-project/issues{/number}",
        "pulls_url": "https://api.github.com/repos/company-group/project-project-project/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/company-group/project-project-project/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/company-group/project-project-project/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/company-group/project-project-project/labels{/name}",
        "releases_url": "https://api.github.com/repos/company-group/project-project-project/releases{/id}",
        "deployments_url": "https://api.github.com/repos/company-group/project-project-project/deployments",
        "created_at": "2017-03-11T22:06:17Z",
        "updated_at": "2020-09-07T17:43:40Z",
        "pushed_at": "2020-09-09T05:16:47Z",
        "git_url": "git://github.com/company-group/project-project-project.git",
        "ssh_url": "git@github.com:company-group/project-project-project.git",
        "clone_url": "https://github.com/company-group/project-project-project.git",
        "svn_url": "https://github.com/company-group/project-project-project",
        "homepage": "http://codeserver.devfactory.com",
        "size": 123370,
        "stargazers_count": 1,
        "watchers_count": 1,
        "language": "Java",
        "has_issues": false,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "forks_count": 3,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 3,
        "license": null,
        "forks": 3,
        "open_issues": 3,
        "watchers": 1,
        "default_branch": "master",
        "allow_squash_merge": true,
        "allow_merge_commit": false,
        "allow_rebase_merge": false,
        "delete_branch_on_merge": false
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/company-group/project-project-project/pulls/1832"
      },
      "html": {
        "href": "https://github.com/company-group/project-project-project/pull/1832"
      },
      "issue": {
        "href": "https://api.github.com/repos/company-group/project-project-project/issues/1832"
      },
      "comments": {
        "href": "https://api.github.com/repos/company-group/project-project-project/issues/1832/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/company-group/project-project-project/pulls/1832/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/company-group/project-project-project/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/company-group/project-project-project/pulls/1832/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/company-group/project-project-project/statuses/990cc7fbf549145e5264c1b9a31ff9dd6d8bfea4"
      }
    },
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "merged": false,
    "mergeable": null,
    "rebaseable": null,
    "mergeable_state": "draft",
    "merged_by": null,
    "comments": 0,
    "review_comments": 0,
    "maintainer_can_modify": false,
    "commits": 1,
    "additions": 158,
    "deletions": 4,
    "changed_files": 9
  },
  "repository": {
    "id": 84682874,
    "node_id": "MDEwOlJlcG9zaXRvcnk4NDY4Mjg3NA==",
    "name": "project-project-project",
    "full_name": "company-group/project-project-project",
    "private": true,
    "owner": {
      "login": "company-group",
      "id": 22237814,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjIyMjM3ODE0",
      "avatar_url": "https://avatars1.githubusercontent.com/u/22237814?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/company-group",
      "html_url": "https://github.com/company-group",
      "followers_url": "https://api.github.com/users/company-group/followers",
      "following_url": "https://api.github.com/users/company-group/following{/other_user}",
      "gists_url": "https://api.github.com/users/company-group/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/company-group/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/company-group/subscriptions",
      "organizations_url": "https://api.github.com/users/company-group/orgs",
      "repos_url": "https://api.github.com/users/company-group/repos",
      "events_url": "https://api.github.com/users/company-group/events{/privacy}",
      "received_events_url": "https://api.github.com/users/company-group/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/company-group/project-project-project",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/company-group/project-project-project",
    "forks_url": "https://api.github.com/repos/company-group/project-project-project/forks",
    "keys_url": "https://api.github.com/repos/company-group/project-project-project/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/company-group/project-project-project/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/company-group/project-project-project/teams",
    "hooks_url": "https://api.github.com/repos/company-group/project-project-project/hooks",
    "issue_events_url": "https://api.github.com/repos/company-group/project-project-project/issues/events{/number}",
    "events_url": "https://api.github.com/repos/company-group/project-project-project/events",
    "assignees_url": "https://api.github.com/repos/company-group/project-project-project/assignees{/user}",
    "branches_url": "https://api.github.com/repos/company-group/project-project-project/branches{/branch}",
    "tags_url": "https://api.github.com/repos/company-group/project-project-project/tags",
    "blobs_url": "https://api.github.com/repos/company-group/project-project-project/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/company-group/project-project-project/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/company-group/project-project-project/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/company-group/project-project-project/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/company-group/project-project-project/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/company-group/project-project-project/languages",
    "stargazers_url": "https://api.github.com/repos/company-group/project-project-project/stargazers",
    "contributors_url": "https://api.github.com/repos/company-group/project-project-project/contributors",
    "subscribers_url": "https://api.github.com/repos/company-group/project-project-project/subscribers",
    "subscription_url": "https://api.github.com/repos/company-group/project-project-project/subscription",
    "commits_url": "https://api.github.com/repos/company-group/project-project-project/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/company-group/project-project-project/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/company-group/project-project-project/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/company-group/project-project-project/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/company-group/project-project-project/contents/{+path}",
    "compare_url": "https://api.github.com/repos/company-group/project-project-project/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/company-group/project-project-project/merges",
    "archive_url": "https://api.github.com/repos/company-group/project-project-project/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/company-group/project-project-project/downloads",
    "issues_url": "https://api.github.com/repos/company-group/project-project-project/issues{/number}",
    "pulls_url": "https://api.github.com/repos/company-group/project-project-project/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/company-group/project-project-project/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/company-group/project-project-project/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/company-group/project-project-project/labels{/name}",
    "releases_url": "https://api.github.com/repos/company-group/project-project-project/releases{/id}",
    "deployments_url": "https://api.github.com/repos/company-group/project-project-project/deployments",
    "created_at": "2017-03-11T22:06:17Z",
    "updated_at": "2020-09-07T17:43:40Z",
    "pushed_at": "2020-09-09T05:16:47Z",
    "git_url": "git://github.com/company-group/project-project-project.git",
    "ssh_url": "git@github.com:company-group/project-project-project.git",
    "clone_url": "https://github.com/company-group/project-project-project.git",
    "svn_url": "https://github.com/company-group/project-project-project",
    "homepage": "http://codeserver.devfactory.com",
    "size": 123370,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "Java",
    "has_issues": false,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 3,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 3,
    "license": null,
    "forks": 3,
    "open_issues": 3,
    "watchers": 1,
    "default_branch": "master"
  },
  "organization": {
    "login": "company-group",
    "id": 22237814,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjIyMjM3ODE0",
    "url": "https://api.github.com/orgs/company-group",
    "repos_url": "https://api.github.com/orgs/company-group/repos",
    "events_url": "https://api.github.com/orgs/company-group/events",
    "hooks_url": "https://api.github.com/orgs/company-group/hooks",
    "issues_url": "https://api.github.com/orgs/company-group/issues",
    "members_url": "https://api.github.com/orgs/company-group/members{/member}",
    "public_members_url": "https://api.github.com/orgs/company-group/public_members{/member}",
    "avatar_url": "https://avatars1.githubusercontent.com/u/22237814?v=4",
    "description": ""
  },
  "sender": {
    "login": "seregamorph",
    "id": 2844909,
    "node_id": "MDQ6VXNlcjM3MzE3OTIw",
    "avatar_url": "https://avatars0.githubusercontent.com/u/2844909?s=88&v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/seregamorph",
    "html_url": "https://github.com/seregamorph",
    "followers_url": "https://api.github.com/users/seregamorph/followers",
    "following_url": "https://api.github.com/users/seregamorph/following{/other_user}",
    "gists_url": "https://api.github.com/users/seregamorph/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/seregamorph/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/seregamorph/subscriptions",
    "organizations_url": "https://api.github.com/users/seregamorph/orgs",
    "repos_url": "https://api.github.com/users/seregamorph/repos",
    "events_url": "https://api.github.com/users/seregamorph/events{/privacy}",
    "received_events_url": "https://api.github.com/users/seregamorph/received_events",
    "type": "User",
    "site_admin": false
  }
}
```

**Comment by seregamorph** [comment]
BTW to workaround it I do weird thing: via reflection set `GHPullRequest.fetchedIssueDetails` to `true`

**Comment by bitwiseman** [comment]
Yeah, that is not great behavior.  
`GHPullRequest` is depending on `GHIssue` to make sure some fields are populated.  This should probably be a check whether `labels` is `null` as with a number of other `populate()` behaviors.

**Comment by seregamorph** [comment]
Resolved in https://github.com/hub4j/github-api/commit/8267050f06c2fa2d35371adb0ba7ae30f55a3e08
