### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/introspect/VisibilityChecker

### ISSUE THREAD

**Issue by Lisius96** [hub4j/github-api#989]
When I try to execute this statement: GitHub github = new GitHubBuilder().withOAuthToken(token).build();  by authenticating myself through personal access tokens, this exception is raised:
 Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/introspect/VisibilityChecker
	at org.kohsuke.github.GitHub.<init>(GitHub.java:115)
	at org.kohsuke.github.GitHubBuilder.build(GitHubBuilder.java:423)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.introspect.VisibilityChecker

**Comment by bitwiseman** [comment]
@Lisius96 
Please describe your configuration.  What versions of github-api and Jackson are you using?  Also, is there more to that callstack?
